[build]
builder = "nixpacks"

[deploy]
startCommand = "cd eventProject && gunicorn eventProject.wsgi --bind 0.0.0.0:$PORT --log-file -"
healthcheckPath = "/graphql"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
