# Generated by Django 6.0.3 on 2026-03-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
